apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: node-app
  name: node-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      run: node-app
  strategy: {}
  template:
    metadata:
      labels:
        run: node-app
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
        name: node-app
