apiVersion: v1
kind: Service
metadata:
  labels:
    run: node-app
  name: node-app
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    run: node-app
  type: {{ .Values.service.type }}
