# Default values for node-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: uqudo.azurecr.io/node-app
  tag: latest

imagePullSecrets: []

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000
